name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
        type: string

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: |
        curl -X POST -H 'content-type: application/json' \
        --url 'https://app.harness.io/gateway/pipeline/api/webhook/custom/v2?accountIdentifier=En0sQGNnTDyB2c5ViNDM_Q&orgIdentifier=default&projectIdentifier=Zendesk&pipelineIdentifier=shshhs&triggerIdentifier=test1' \
        -d '{"sample_key": "sample_value"}'
